/*
 * site-search.js — client-side search over the pre-built index
 * (media/search-index.json, generated by tools/build_search_index.py).
 *
 * Scoring: term frequency in body, boosted heavily for title hits and
 * moderately for description hits; all query terms must appear somewhere.
 * Results show a snippet around the first body match with terms highlighted.
 */
(function () {
    "use strict";

    var INDEX_URL = "/media/search-index.json";
    var index = null;
    var input, results, statusEl;

    function init() {
        input = document.getElementById("search-input");
        results = document.getElementById("search-results");
        statusEl = document.getElementById("search-status");
        if (!input || !results) return;

        var t = null;
        input.addEventListener("input", function () {
            clearTimeout(t);
            t = setTimeout(run, 150);
        });
        input.focus();

        // support ?q= links
        var m = window.location.search.match(/[?&]q=([^&]+)/);
        if (m) {
            input.value = decodeURIComponent(m[1].replace(/\+/g, " "));
        }

        statusEl.textContent = "Loading index…";
        fetch(INDEX_URL)
            .then(function (r) { return r.json(); })
            .then(function (d) {
                index = d.map(function (e) {
                    return {
                        url: e.url, title: e.title, desc: e.desc,
                        series: e.series || "", text: e.text,
                        ltitle: e.title.toLowerCase(),
                        ldesc: (e.desc || "").toLowerCase(),
                        ltext: e.text.toLowerCase()
                    };
                });
                statusEl.textContent = index.length + " pages indexed. Type to search.";
                if (input.value) run();
            })
            .catch(function () {
                statusEl.textContent = "Could not load the search index.";
            });
    }

    function tokens(q) {
        return q.toLowerCase().match(/[a-z0-9][a-z0-9'-]*/g) || [];
    }

    function countOccurrences(haystack, needle) {
        var n = 0, pos = 0;
        while ((pos = haystack.indexOf(needle, pos)) !== -1) { n++; pos += needle.length; }
        return n;
    }

    function run() {
        if (!index) return;
        var q = input.value.trim();
        results.innerHTML = "";
        if (q.length < 2) {
            statusEl.textContent = index.length + " pages indexed. Type to search.";
            return;
        }
        var terms = tokens(q);
        if (!terms.length) return;

        var scored = [];
        index.forEach(function (e) {
            var score = 0, allFound = true;
            terms.forEach(function (term) {
                var inTitle = countOccurrences(e.ltitle, term);
                var inDesc = countOccurrences(e.ldesc, term);
                var inBody = countOccurrences(e.ltext, term);
                if (!inTitle && !inDesc && !inBody) { allFound = false; return; }
                score += inTitle * 30 + inDesc * 10 + Math.min(inBody, 12);
            });
            // phrase bonus for multi-term queries
            if (allFound && terms.length > 1) {
                var phrase = terms.join(" ");
                if (e.ltitle.indexOf(phrase) !== -1) score += 60;
                else if (e.ltext.indexOf(phrase) !== -1) score += 25;
            }
            if (allFound) scored.push({ e: e, score: score });
        });

        scored.sort(function (a, b) { return b.score - a.score; });
        var top = scored.slice(0, 20);

        statusEl.textContent = scored.length
            ? scored.length + " page" + (scored.length === 1 ? "" : "s") + " matched."
            : "No pages matched “" + q + "”.";

        top.forEach(function (item) {
            results.appendChild(renderResult(item.e, terms));
        });
    }

    function renderResult(e, terms) {
        var li = document.createElement("li");
        li.className = "search-result";

        var a = document.createElement("a");
        a.href = e.url;
        a.className = "search-result-title";
        a.textContent = e.title.replace(/ — Adrian Mag$/, "");
        li.appendChild(a);

        if (e.series) {
            var chip = document.createElement("span");
            chip.className = "search-result-series";
            chip.textContent = e.series;
            li.appendChild(chip);
        }

        var snip = document.createElement("p");
        snip.className = "search-result-snippet";
        snip.innerHTML = snippet(e, terms);
        li.appendChild(snip);
        return li;
    }

    function escapeHtml(s) {
        return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
    }

    function snippet(e, terms) {
        // find the earliest body occurrence of any term
        var best = -1;
        terms.forEach(function (t) {
            var pos = e.ltext.indexOf(t);
            if (pos !== -1 && (best === -1 || pos < best)) best = pos;
        });
        var raw;
        if (best === -1) {
            raw = e.desc || e.text.slice(0, 180);
        } else {
            var start = Math.max(0, best - 70);
            raw = (start > 0 ? "…" : "") + e.text.slice(start, best + 130) + "…";
        }
        var safe = escapeHtml(raw);
        terms.forEach(function (t) {
            safe = safe.replace(new RegExp("(" + t.replace(/[.*+?^${}()|[\]\\]/g, "\\$&") + ")", "gi"),
                "<mark>$1</mark>");
        });
        return safe;
    }

    if (document.readyState === "loading") {
        document.addEventListener("DOMContentLoaded", init);
    } else {
        init();
    }
})();
